language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install -e .[dev]
before_script:
  - make codeclime-install codeclime-pre-build
script:
  - make lint test
after_success:
  - make codacy coveralls codecov codeclime
